name: Publish private GenAI-utils package 

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Package version that you want to release."
        required: false 
        type: string
  
jobs:
  publish-package:
    runs-on: ubuntu-latest 

    steps:
      - name: greeting
        run: echo "Hello, this workflow will publish the GenAI-utils package to the private registry. Please make sure you have the necessary permissions and credentials set up before proceeding."
      - name: print package version
        run: echo "Released package version is ${{ inputs.tag_name}}"
      - name: goodbye
        run: echo "Goodbye, the workflow has completed. If you have any questions or need further assistance, please don't hesitate to reach out."